### ISSUE TITLE
comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [EmilianoMora/ProyectoFinalBioinf2018-II#1]
Porfas modifica el avance 1 para incluir los links a los datos que mencionas.

**Comment by EmilianoMora** [comment]
Listo!

No había visto este comentario. Una disculpa.

**Comment by AliciaMstt** [comment]
Mmmm el link que pusiste solo funciona dentro de la unam (checa como se puso una redirección que dice unam dentro de la url)
